---
kind: Kustomization
namespace: justorderit

commonLabels:
  app: justorderit

resources:
  - namespace.yml
  - secrets.yml
  - backend
  - redis
  - frontend

configMapGenerator:
  - name: common-config
    literals:
      - DB_HOST=sontaran-main-cluster.postgres.svc.cluster.local
      - REDIS_HOST=redis.justorderit.svc.cluster.local

images:
  - name: registry.cri.epita.fr/damien.champeyroux/justorderit
    newTag: 1.0.3-SNAPSHOT
  - name: registry.cri.epita.fr/damien.champeyroux/justorderitfront
    newTag: latest
