---
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: sontaran-main-cluster
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
spec:
  teamId: sontaran
  volume:
    size: 10Gi
  numberOfInstances: 3

  # users: name -> permissions (usually [])
  users:
    justorderit.backend: []
    fraternity.frat_logs: []
    gastbob40: []

  # databases: name -> owner
  databases:
    justorderit_backend: justorderit.backend
    fraternity_frat_logs: fraternity.frat_logs

  postgresql:
    version: "13"
    parameters:
      max_connections: "500"

  resources:
    requests:
      cpu: "2"
      memory: "2G"
    limits:
      cpu: "4"
      memory: "4G"

  additionalVolumes:
    - name: pgbackup
      mountPath: /home/postgres/pgbackup
      volumeSource:
        emptyDir: {}
