---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "justorderit-backend-ingress-cert"
  namespace: "justorderit"
spec:
  commonName: "backend.justorderit.sontaran.gastbob40.ovh"
  secretName: "justorderit-backend-ingress-cert-secret"
  dnsNames:
    - "backend.justorderit.sontaran.gastbob40.ovh"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "justorderit-backend-ingress"
  namespace: "justorderit"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "backend.justorderit.sontaran.gastbob40.ovh"
      secretName: "justorderit-backend-ingress-cert-secret"
  rules:
    - host: "backend.justorderit.sontaran.gastbob40.ovh"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "backend"
                port:
                  number: 8080
  
