{{- range $ingress := .Values.ingresses }}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ $ingress.name }}-ingress-cert"
  namespace: "{{ $ingress.namespace }}"
spec:
  commonName: "{{ $ingress.host }}"
  secretName: "{{ $ingress.name }}-ingress-cert-secret"
  dnsNames:
    - "{{ $ingress.host }}"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ $ingress.name }}-ingress"
  namespace: "{{ $ingress.namespace }}"

  {{ if or ($ingress.basicAuth).enabled (hasKey $ingress "annotations") }}
  annotations:
    {{ if (($ingress.basicAuth).enabled) }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: "{{ $ingress.basicAuth.secret }}"
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
    {{ end }}

    {{ range $key, $value := $ingress.annotations }}
    {{ $key }}: "{{ $value }}"
    {{ end }}
  {{ end }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "{{ $ingress.host }}"
      secretName: "{{ $ingress.name }}-ingress-cert-secret"
  rules:
    - host: "{{ $ingress.host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ $ingress.service }}"
                port:
                  number: {{ $ingress.port }}

{{- end }}
