apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: redis
    component: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
      labels:
        name: redis
        component: redis
    spec:
      containers:
        - name: redis
          image: redis
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
              name: redis
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 110m
              memory: 110Mi
