apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-ingress
  namespace: argocd
spec:
  project: default
  source:
    path: k8s/cluster/cluster-ingress
    repoURL: https://github.com/gastbob40/tardis-overcloud.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    namespace: cluster-ingress
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
