apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-misc
  namespace: argocd
spec:
  project: default
  source:
    path: k8s/cluster/cluster-misc
    repoURL: https://gitlab.cri.epita.fr/ing/majeures/ice/ice-cloud.git
    targetRevision: HEAD
  destination:
    namespace: cluster-misc
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
