apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-misc
  namespace: argocd
spec:
  project: default
  source:
    path: k8s/cluster/cluster-misc
    repoURL: https://github.com/gastbob40/tardis-overcloud.git
    targetRevision: HEAD
  destination:
    namespace: cluster-misc
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
