apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: default
  source:
    path: k8s/cluster/postgres
    repoURL: https://gitlab.cri.epita.fr/ing/majeures/ice/ice-cloud.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    namespace: postgres
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
