apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-operator
  namespace: argocd
spec:
  project: default
  source:
    path: k8s/cluster/vault-secrets-operator
    repoURL: https://github.com/gastbob40/tardis-overcloud.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    namespace: vault-secrets-operator
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
